// <auto-generated />
namespace Revit.Api.Azure.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class DBV01 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DBV01));
        
        string IMigrationMetadata.Id
        {
            get { return "201607172204049_DB-V0.1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
