//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Revit.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Person()
        {
            this.ProcedureEnrollment = new HashSet<ProcedureEnrollment>();
        }
    
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Gender { get; set; }
        public string Nationality { get; set; }
        public string NationalNr { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string DriversLicence { get; set; }
        public bool HasDisabilities { get; set; }
        public bool RequiresFollowup { get; set; }
        public string PreferredLanguageCode { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime UpdatedOn { get; set; }
        public long TransactionalVersion { get; set; }
        public string ERecruitingUsername { get; set; }
        public System.Guid GlobalId { get; set; }
        public string AddressLine1 { get; set; }
        public string AddressLine2 { get; set; }
        public string AddressLine3 { get; set; }
        public string ZipCode { get; set; }
        public string Town { get; set; }
        public string CountryCode { get; set; }
        public string PhoneNumber { get; set; }
        public bool PhoneNumberIsMobile { get; set; }
        public string AltPhoneNumber { get; set; }
        public bool AltPhoneNumberIsMobile { get; set; }
        public string Email { get; set; }
        public string Comments { get; set; }
        public string NativeLanguageCode { get; set; }
        public string GenderNeutral { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProcedureEnrollment> ProcedureEnrollment { get; set; }
    }
}
