//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Revit.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SelorBusiness_SOCEntities : DbContext
    {
        public SelorBusiness_SOCEntities()
            : base("name=SelorBusiness_SOCEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Procedure> Procedure { get; set; }
        public virtual DbSet<ProcedureEnrollment> ProcedureEnrollment { get; set; }
        public virtual DbSet<ProcedureEnrollmentStatus> ProcedureEnrollmentStatus { get; set; }
        public virtual DbSet<Target> Target { get; set; }
        public virtual DbSet<TargetCriteria> TargetCriteria { get; set; }
        public virtual DbSet<TargetType> TargetType { get; set; }
        public virtual DbSet<Test> Test { get; set; }
        public virtual DbSet<TestSessionEnrollment> TestSessionEnrollment { get; set; }
        public virtual DbSet<TestSessionEnrollmentStatus> TestSessionEnrollmentStatus { get; set; }
        public virtual DbSet<Person> Person { get; set; }
        public virtual DbSet<TargetResult> TargetResult { get; set; }
    }
}
