//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Revit.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Target
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Target()
        {
            this.Target1 = new HashSet<Target>();
            this.TargetCriteria = new HashSet<TargetCriteria>();
            this.Test = new HashSet<Test>();
        }
    
        public int Id { get; set; }
        public string Code { get; set; }
        public string Name_nl { get; set; }
        public string Name_fr { get; set; }
        public string Name_de { get; set; }
        public string Name_en { get; set; }
        public Nullable<double> DefaultCaesuraMinValue { get; set; }
        public Nullable<double> DefaultCaesuraMaxValue { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime UpdatedOn { get; set; }
        public long TransactionalVersion { get; set; }
        public int TypeId { get; set; }
        public Nullable<int> ParentId { get; set; }
        public bool IsAutoValidatingResults { get; set; }
        public string Description_nl { get; set; }
        public string Description_fr { get; set; }
        public string Description_de { get; set; }
        public string Description_en { get; set; }
        public string ModuleType { get; set; }
        public string ModuleLevel { get; set; }
        public bool AllowMultipleTestSessionEnrollments { get; set; }
        public bool Archived { get; set; }
        public System.Guid GlobalId { get; set; }
        public bool IsValidationTarget { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Target> Target1 { get; set; }
        public virtual Target Target2 { get; set; }
        public virtual TargetType TargetType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TargetCriteria> TargetCriteria { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Test> Test { get; set; }
    }
}
