//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Revit.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TargetResult
    {
        public int Id { get; set; }
        public string NationalNr { get; set; }
        public string SelectionCode { get; set; }
        public string TestCode { get; set; }
        public string TargetCode { get; set; }
        public bool IsActual { get; set; }
        public double Score { get; set; }
        public System.DateTime SessionStartedOn { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string Feedback { get; set; }
        public Nullable<bool> IsPassed { get; set; }
        public Nullable<System.DateTime> ProcessedOn { get; set; }
        public bool IsExempting { get; set; }
        public bool IsBuffering { get; set; }
    }
}
