//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Revit.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TargetCriteria
    {
        public int Id { get; set; }
        public int TargetId { get; set; }
        public Nullable<int> CertificateId { get; set; }
        public Nullable<double> CaesuraMaxValue { get; set; }
        public Nullable<double> CaesuraMinValue { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime UpdatedOn { get; set; }
        public long TransactionalVersion { get; set; }
        public Nullable<int> SelectionApproachId { get; set; }
        public int CommunicationTypeId { get; set; }
        public bool CaesuraMinValueChanged { get; set; }
        public bool CaesuraMaxValueChanged { get; set; }
    
        public virtual Target Target { get; set; }
    }
}
