//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Revit.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestSessionEnrollment
    {
        public int Id { get; set; }
        public string AbsenceMotivation { get; set; }
        public System.DateTime Appointment { get; set; }
        public System.DateTime SubscribedSince { get; set; }
        public Nullable<int> EnrollmentStatusId { get; set; }
        public int EventId { get; set; }
        public int ProcedureEnrollmentId { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime UpdatedOn { get; set; }
        public long TransactionalVersion { get; set; }
        public int TestId { get; set; }
        public string ADM_ex_code { get; set; }
        public bool NotifyCandidate { get; set; }
    
        public virtual ProcedureEnrollment ProcedureEnrollment { get; set; }
        public virtual Test Test { get; set; }
        public virtual TestSessionEnrollmentStatus TestSessionEnrollmentStatus { get; set; }
    }
}
