//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Revit.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Test
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Test()
        {
            this.TestSessionEnrollment = new HashSet<TestSessionEnrollment>();
            this.Target = new HashSet<Target>();
        }
    
        public int Id { get; set; }
        public string TestCode { get; set; }
        public string Name_nl { get; set; }
        public string Name_fr { get; set; }
        public string Name_de { get; set; }
        public string Name_en { get; set; }
        public string Description_nl { get; set; }
        public string Description_fr { get; set; }
        public string Description_de { get; set; }
        public string Description_en { get; set; }
        public bool IsActive { get; set; }
        public Nullable<double> MaximumDurationHours { get; set; }
        public Nullable<int> TestPlatformId { get; set; }
        public string TestMethodCode { get; set; }
        public Nullable<double> ParticipationLimitationFrequenceValue { get; set; }
        public string ParticipationLimitationFrequenceUnitTypeCode { get; set; }
        public string ParticipationLimitationTypeCode { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime UpdatedOn { get; set; }
        public long TransactionalVersion { get; set; }
        public Nullable<int> ResultEntryTestId { get; set; }
        public Nullable<int> SaltoId { get; set; }
        public bool Archived { get; set; }
        public string LanguageCode { get; set; }
        public Nullable<int> TestGroupId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TestSessionEnrollment> TestSessionEnrollment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Target> Target { get; set; }
    }
}
